### PR TITLE
Fix lifetime issues

### LINKED ISSUE #293: Valgrind warnings when running tests (use after free)
Bisected down to this commit: https://github.com/rpm-software-management/createrepo_c/commit/670006b9f37d8298fe2ec1d6cfc5cdf175a3128b#

`valgrind --leak-check=full --show-leak-kinds=definite pytest --verbose ./tests/python/tests/test_xml_parser.py::TestCaseXmlParserFilelists::test_xml_parser_filelists_warningcb_abort`

```
==59182== Invalid read of size 8                                                                                       
==59182==    at 0x8A1754A: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637)                                                    
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)
==59182==    by 0x8D8D3A8: xmlParseChunk (parser.c:12346)
==59182==    by 0x8A1D7A5: cr_xml_parser_generic (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A176D5: cr_xml_parse_filelists_internal (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A17776: cr_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A053E9: py_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x496D3D7: cfunction_call (methodobject.c:552)
==59182==    by 0x4968FB3: _PyObject_MakeTpCall (call.c:215)          
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:112)
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:99)                                                                                                                                                                                  
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:123)                                                                                                                                                                                 
==59182==    by 0x4965C8C: UnknownInlinedFun (ceval.c:5888)                                                                                                                                                                                   
==59182==    by 0x4965C8C: _PyEval_EvalFrameDefault (ceval.c:4189)
==59182==    by 0x495EE43: UnknownInlinedFun (pycore_ceval.h:46)
==59182==    by 0x495EE43: _PyEval_Vector (ceval.c:5073)
==59182==  Address 0x581fa98 is 24 bytes inside a block of size 328 free'd
==59182==    at 0x48430E4: free (vg_replace_malloc.c:872)                                                              
==59182==    by 0x8B3A0BC: g_free (gmem.c:199)           
==59182==    by 0x89FFF34: package_dealloc (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A04CE6: c_newpkgcb (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A171B6: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637) 
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)
==59182==    by 0x8D8D3A8: xmlParseChunk (parser.c:12346)                                                              
==59182==    by 0x8A1D7A5: cr_xml_parser_generic (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                          
==59182==    by 0x8A176D5: cr_xml_parse_filelists_internal (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A17776: cr_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A053E9: py_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==  Block was alloc'd at
==59182==    at 0x4845464: calloc (vg_replace_malloc.c:1328)
==59182==    by 0x8B3DCB0: g_malloc0 (gmem.c:136)
==59182==    by 0x8A0D6CB: cr_package_new (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A00119: package_init (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x4969202: type_call (typeobject.c:1128)
==59182==    by 0x4968FB3: _PyObject_MakeTpCall (call.c:215)
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:112)
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:99)
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:123)
==59182==    by 0x4965C8C: UnknownInlinedFun (ceval.c:5888) 
==59182==    by 0x4965C8C: _PyEval_EvalFrameDefault (ceval.c:4189)
==59182==    by 0x495EE43: UnknownInlinedFun (pycore_ceval.h:46)
==59182==    by 0x495EE43: _PyEval_Vector (ceval.c:5073)
==59182==    by 0x8A04BEC: c_newpkgcb (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A171B6: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637) 
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)
==59182== 
```

```
==59182== Invalid write of size 8                                                                                                                                                                                                             
==59182==    at 0x8A17520: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)      
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637)                                                                                                                                                                                   
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)                                                                                                                                                                        
==59182==    by 0x8D8D3A8: xmlParseChunk (parser.c:12346)                                                                                                                                                                                     
==59182==    by 0x8A1D7A5: cr_xml_parser_generic (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                           
==59182==    by 0x8A176D5: cr_xml_parse_filelists_internal (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                 
==59182==    by 0x8A17776: cr_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                          
==59182==    by 0x8A053E9: py_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                          
==59182==    by 0x496D3D7: cfunction_call (methodobject.c:552)                                                                                                                                                                                
==59182==    by 0x4968FB3: _PyObject_MakeTpCall (call.c:215)                                                                                                                                                                                  
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:112)                                                                                                                                                                                 
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:99)                                                                                                                                                                                  
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:123)                                                                                                                                                                                 
==59182==    by 0x4965C8C: UnknownInlinedFun (ceval.c:5888)                                                                                                                                                                                   
==59182==    by 0x4965C8C: _PyEval_EvalFrameDefault (ceval.c:4189)                                                                                                                                                                            
==59182==    by 0x495EE43: UnknownInlinedFun (pycore_ceval.h:46)                                                                                                                                                                              
==59182==    by 0x495EE43: _PyEval_Vector (ceval.c:5073)                                                                                                                                                                                      
==59182==  Address 0x581fa88 is 8 bytes inside a block of size 328 free'd                                                                                                                                                                     
==59182==    at 0x48430E4: free (vg_replace_malloc.c:872)                                                                                                                                                                                     
==59182==    by 0x8B3A0BC: g_free (gmem.c:199)                                                                                                                                                                                                
==59182==    by 0x89FFF34: package_dealloc (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                                 
==59182==    by 0x8A04CE6: c_newpkgcb (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                     
==59182==    by 0x8A171B6: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                                
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637)                                                                                                                                                                                   
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)                                                                                                                                                                        
==59182==    by 0x8D8D3A8: xmlParseChunk (parser.c:12346)                                                                                                                                                                                     
==59182==    by 0x8A1D7A5: cr_xml_parser_generic (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                           
==59182==    by 0x8A176D5: cr_xml_parse_filelists_internal (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                 
==59182==    by 0x8A17776: cr_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x8A053E9: py_xml_parse_filelists (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                          
==59182==  Block was alloc'd at                                                                                                                                                                                                               
==59182==    at 0x4845464: calloc (vg_replace_malloc.c:1328)                                                                                                                                                                                  
==59182==    by 0x8B3DCB0: g_malloc0 (gmem.c:136)                                                                                                                                                                                             
==59182==    by 0x8A0D6CB: cr_package_new (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                                  
==59182==    by 0x8A00119: package_init (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)
==59182==    by 0x4969202: type_call (typeobject.c:1128)                                                               
==59182==    by 0x4968FB3: _PyObject_MakeTpCall (call.c:215)                                                                                                                                                                                  
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:112)                                                                                                                                                                                 
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:99)                                                                                                                                                                                  
==59182==    by 0x4965C8C: UnknownInlinedFun (abstract.h:123)                                                                                                                                                                                 
==59182==    by 0x4965C8C: UnknownInlinedFun (ceval.c:5888)             
==59182==    by 0x4965C8C: _PyEval_EvalFrameDefault (ceval.c:4189)                                                                                                                                                                            
==59182==    by 0x495EE43: UnknownInlinedFun (pycore_ceval.h:46)                                                                                                                                                                              
==59182==    by 0x495EE43: _PyEval_Vector (ceval.c:5073)                                                                                                                                                                                      
==59182==    by 0x8A04BEC: c_newpkgcb (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                                      
==59182==    by 0x8A171B6: cr_start_handler (in /home/vagrant/.env/lib/python3.10/site-packages/createrepo_c/_createrepo_c.so)                                                                                                                
==59182==    by 0x8D8904B: xmlParseStartTag (parser.c:8637)                                                                                                                                                                                   
==59182==    by 0x8E71E44: xmlParseTryOrFinish.isra.0 (parser.c:11456)                                                                                                                                                                        
==59182==                                                                `
```

### PR DESCRIPTION
**Pull request by dralley**
closes #293

### CODE REVIEW

File: src/package.c [hunk 1]
```diff
@@ -87,11 +87,6 @@ cr_package_free(cr_Package *package)
     if (package->chunk && !(package->loadingflags & CR_PACKAGE_SINGLE_CHUNK))
         g_string_chunk_free (package->chunk);
 
-/* Note: Since glib 2.28
- * g_slist_foreach && g_slist_free could be replaced with one function:
- * g_slist_free_full()
- */
```
Comment (dralley) [inline src/package.c:93]: (Already done)

**Comment by dralley** [comment]
There's still a memory leak somewhere that I will try to hunt down

**Comment by dralley** [comment]
Memry leak fixed, but there's a brand new use-after-free.

File: src/xml_parser_main_metadata_together.c [hunk 2]
```diff
@@ -454,6 +455,10 @@ int cr_xml_parse_main_metadata_together(const char *primary_path,
         }
     }
 
+    cr_package_free(primary_pd->pkg);
+    cr_package_free(filelists_pd->pkg);
+    cr_package_free(other_pd->pkg);
```
Comment (dralley) [inline src/xml_parser_main_metadata_together.c:460]: Does this need the same checks as e.g. https://github.com/rpm-software-management/createrepo_c/blob/master/src/xml_parser_filelists.c#L364-L372

File: src/python/xml_parser-py.c [hunk 3]
```diff
@@ -69,14 +69,10 @@ c_newpkgcb(cr_Package **pkg,
         *pkg = NULL;
     } else {
         *pkg = Package_FromPyObject(result);
-        if (data->py_pkgcb != Py_None) {
-            // Store reference to the python pkg (result) only if we will need it later
-            PyObject *keyFromPtr = PyLong_FromVoidPtr(*pkg);
-            PyDict_SetItem(data->py_pkgs, keyFromPtr, result);
-            Py_DECREF(keyFromPtr);
-        }
```
Comment (dralley) [inline src/python/xml_parser-py.c:77]: In the event that there is no `py_pkgcb`, the only reference to the underlying `cr_Package` is held via `result`, and that refcount goes to 0 on line 80 below, and it gets freed.  But since this is `newpkgcb` this the package isn't finished being parsed yet so the parsing code is writing to a dead object.

The code used to wait until the next iteration (once the package has finished parsing) before decrementing the refcount, so it was safe: https://github.com/rpm-software-management/createrepo_c/commit/670006b9f37d8298fe2ec1d6cfc5cdf175a3128b#diff-0a3304524b67e6c30420cf0bd3f66c5937250b1e6837414a0d9d0ea5bc87ab63L52

Since the reference needs to be stored no matter what, I just picked the approach of simplifying the codepaths and using one method, but let me know if you have something else in mind.

**Comment by dralley** [comment]
There's a few more minor memory leaks that happeon only on error paths, that I gave up on trying to fix.  Not a huge deal.

But TL;DR if an error is encountered the package currently being parsed is never free'd properly.

File: src/python/xml_parser-py.c (hunk 3 above)
Comment (kontura) [reply src/python/xml_parser-py.c:77]: I see, that is a good catch!
I would prefer a different solution tough.

Because if we do this then anytime we use the API without `py_pkgcb` we store all the packages in memory throughout the run because `data->py_pkgs` is cleared only in the `py_pkgcb` callback (not set here) or at the very end so at that point we might as well use the old API.
It would also be pointless work to parse the pkg in such a case since we know the user doesn't have any reference to it and has no way to get it either since there is no `py_pkgcb` (at least for this version of the API).

Right now it would make most sense to me to check if the package gets freed by the `Py_DECREF` and if so set `*pkg` to `NULL` to skip the package.

Perhaps the end of the function could look like this (not sure if there is some better way to do this)?
```
     if (result->ob_refcnt == 1) {
          *pkg = NULL;
     }
     Py_DECREF(result);

     return CR_CB_RET_OK;
```

Comment (dralley) [reply src/python/xml_parser-py.c:77]: It feels a little unsatisfying but I'm not sure of a better way.  I've made the change though and Valgrind passes (apart from the one issue I mentioned already below)
